# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
joint1:
  ID: 1
joint2:
  ID: 2
joint3:
  ID: 3
joint4:
  ID: 4
joint5:
  ID: 5
joint6:
  ID: 6



