# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 2.0
joint1:
  ID: 1
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 0
joint2:
  ID: 2
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 0
joint3:
  ID: 3
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 0
joint4:
  ID: 4
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 0
joint5:
  ID: 5
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 0


