joint:
  names: [one, two, three, four, five]
motion:
  names: [right, up, up2, yes]
  right:
    step: [0, 0.6,0.4,-1.7,-1]  # radian
    time_from_start: 2.0  # sec
  up:
    step: [0.3,-0.85, 0.9,0.2,-1.6]  # radian
    time_from_start: 3.0  # sec
  up2:
    step: [0.3,-0.85, 0.9,0.2,-1.6]  # radian
    time_from_start: 4.0  # sec
  yes:
    step: [0, 0.6,0.4,-1.7,-1]  # radian
    time_from_start: 6.0  # sec

