joint:
  names: [one, two, three, four, five]
motion:
  names: [start, reach1, reach2, backto_start]
  start:
    step: [0, 0.6,0.4,-1.7,-1]  # radian
    time_from_start: 2.0  # sec
  reach1:
    step: [0,-0.5, 1.2,-0.3,-1.7]  # radian
    time_from_start: 3.0  # sec
  reach2:
    step: [0,-0.85, 0.9,0.2,-1.6]  # radian
    time_from_start: 4.0  # sec
  backto_start:
    step: [0, 0.6,0.4,-1.7,-1]  # radian
    time_from_start: 6.0  # sec


