joint:
  names: [joint1, joint2, joint3, joint4, joint5, joint6]
motion:
  names: [default, step2]
  default:
    step: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # radian
    time_from_start: 15.0  # sec
  step2:
    step: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # radian
    time_from_start: 20.0  # sec


